Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -22,8 +22,17 @@ steps:
 
 # Installation des dépendances
 - script: |
-    npm install
+    echo "Installing dependencies..."
+    npm ci
+    if [ $? -ne 0 ]; then
+      echo "npm ci failed. Exiting..."
+      exit 1
+    fi
     npm install -g @angular/cli
+    if [ $? -ne 0 ]; then
+      echo "npm install -g @angular/cli failed. Exiting..."
+      exit 1
+    fi
   displayName: 'Install dependencies'
 
 # Compilation TypeScript et build du projet Angular
